# Generated by Django 3.2.5 on 2022-12-05 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idPelicula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy mala'), (2, 'Mala'), (3, 'Regular'), (4, 'Buena'), (5, 'Muy Buena')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigoPostal',
            field=models.CharField(max_length=6, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveSmallIntegerField(help_text='Debe introducir una edad', verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Debe elegir entre M o F', max_length=1, verbose_name='Sexo'),
        ),
    ]
