# Generated by Django 4.1.1 on 2022-12-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221205_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('IdArtista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Artista')),
                ('Url', models.URLField(verbose_name='URL')),
                ('PictureUrl', models.URLField(verbose_name='URL de la foto')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('IdTag', models.IntegerField(primary_key=True, serialize=False)),
                ('TagValue', models.CharField(max_length=30, verbose_name='Valor de la etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuario', models.IntegerField(verbose_name='Id del usuario')),
                ('TiempoEscucha', models.IntegerField(verbose_name='Tiempo de escucha')),
                ('IdArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEtiquetaArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuario', models.IntegerField(verbose_name='Id del usuario')),
                ('Dia', models.IntegerField(verbose_name='Día')),
                ('Mes', models.IntegerField(verbose_name='Mes')),
                ('Ano', models.IntegerField(verbose_name='Ano')),
                ('IdArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
                ('IdTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etiqueta')),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='puntuaciones',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idPelicula',
        ),
        migrations.RemoveField(
            model_name='puntuacion',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ocupacion',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Ocupacion',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
